### ISSUE TITLE
qemu_downgrade has begun to fail due to missing package dependency libcrypto++9

### ISSUE THREAD

**Issue by chris-brightman** [asb/spindle#148]
I have been using spindle quite happily to build raspian images for a few weeks. I created a new chroot build in a new ubuntu 14.04 VM today and the qemu downgrade failed due to the missing dependency above. It seems that the dpkg -i command pulls in the required librados2 and librbd1 packages but not libcrypto++9. Has anyone else seen this issue? Manually installing the package allows the qemu downgrade to proceed but I have not had to do this before. Perhaps this is a change in wheezy package versions? I suspect I can fix this myself by adding the library to the pre-reqs installed in the chroot setup but I'm not sure if this should be required.

--- output ---
dpkg: warning: downgrading qemu from 1.1.2+dfsg-6a+deb7u6 to 1.0.1+dfsg-1
Preparing to replace qemu 1.1.2+dfsg-6a+deb7u6 (using qemu_1.0.1+dfsg-1_amd64.deb) ...
Unpacking replacement qemu ...
dpkg: dependency problems prevent configuration of librados2:
 librados2 depends on libcrypto++9; however:
  Package libcrypto++9 is not installed.

dpkg: error processing librados2 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of librbd1:
 librbd1 depends on librados2 (= 0.43-1); however:
  Package librados2 is not configured yet.

**Comment by luckydonald** [comment]
I found `libcrypto++9v5` in ubuntu-server. Maybe a successor?
